### ISSUE TITLE
Using Datepicker

### ISSUE THREAD

**Issue by JxPrince** [eduardotkoller/convForm#1]
Hi @eduardotkoller  , 
I am unable to use jquery datepicker inside Convform. Inside conv-form-wrapper the default date pop-up behaviour is suppressed. Pls suggest how to oversome this.

**Comment by eduardotkoller** [comment]
This happens because jquery datepicker only works on inputs, spans and divs, and the user input for the chat is built as an textarea. I build it as it is because with textarea, it can support multiple lines. If you want, you can make it work in two different ways: 

- Change the jquery datepicker script to work on textareas (you can see more info on that [here](https://stackoverflow.com/questions/4117727/why-jquery-datepicker-doesnt-work-on-textarea-but-only-on-input))
- Change the convForm to be built around a input instead of textarea. For that, you must change the line 218 of the script to something like that: 
`var inputForm = $('<form id="convForm"><div class="options dragscroll"></div><input id="userInput" type="text" placeholder="'+placeholder+'"/><button type="submit" class="icon2-arrow submit">⯈</button><span class="clear"></span></form>');`
