### ISSUE TITLE
Questions and features

### ISSUE THREAD

**Issue by nam-co** [eduardotkoller/convForm#29]
Hi Eduardo, the project its looking good, congrats
I was wondering is it's possible to do this things:

1. is it possible to make the conversation persistent between the different pages, similar to something like drift pop up? for example if I go from home to the about page
2. is it possible to submit using ajax, so for example the server can respond: "thanks, appointment is on Monday 10am", and the user sees the message in the chat
3. does it accept file inputs?

Once again, thanks for your work
Appreciate any help

**Comment by eduardotkoller** [comment]
Hi there, I'm really glad you like the project!

1: Not directly supported by the plugin (needs persistence on server), but you create a persistence effect by building the form on every page based on user's previous answer (you will need to store all answers somewhere like a DB)

2: I just pushed a change that supports this. Please take a look at the api_example.html.

3: No, at last not at the moment.

Sorry for the delay on answering.

**Comment by praveenyadv** [comment]
Hi, this plugin is really Cool, thanks for the effort
i just have a question about your new push, 

how do we go back to the normal conversation state after we are done working with API, for example if i needed to work with API response in middle of normal conversation, how do i go back to the conversation where i started the API calls

thanks again for this push,

**Comment by nam-co** [comment]
Hi @eduardotkoller thanks for the answer

1 persistent: ok if I understand correctly, something like reds or memcached and get the conversation by the user IP address?

2 API: thank you Eduardo
3. hope some day,:) it could be ajax or on submit, with a api message that says: "one moment please while we upload the files" (data-uploading-message), just an idea, I wish a was decent in js so I could help

thanks Eduardo

**Comment by eduardotkoller** [comment]
@nam-co 1: yes

@praveenyadv It's hard to come up with the concept on how to implement this on the plugin, because how do I structure when you want to start using the dynamic building , when to stop and to what question to come back? It's much easier for you to do this on your end, like building the entire conversation based on the answers (that way you can build the states to follow the exact sequence you want and have more freedom to when enter a loop, when to process the answer to build another question based on it, when to just get the answer and go to the next question independent on the answer). I will think on a way to implement this on the plugin, but I have to look at necessity x quality of life and if it's worth implementing it.
