### ISSUE TITLE
How to dynamically insert input fields as a Reply

### ISSUE THREAD

**Issue by vijayrajasekaran** [eduardotkoller/convForm#5]
Hello,

I am able to dynamically create an Input Field when asking the initial question. But when I try to get the User's reply, Process it in the back-end server and Send a reply to the front-end, I am unable to create a New Input Field as a Reply.
```
<form id="form" onsubmit="form(); return false;" method="POST" class="hidden">
  <!-- Form Fields will be created dynamically here -->
</form>
```

```
    <script>
        $('#form').append('<input type="text" id="question" name="question" conv-question="What is your name?">');
        function form() {
            var form = document.getElementById('form');
            var question = form.elements.question.value;
                $.post("/answer",
                    {
                        question: question
                    },
                    function(data){
                      $("<input type='text' />")
                         .attr("id", "answer")
                         .attr("name", "answer")
                         .attr("conv-question", data)
                         .appendTo("#form");
                });
        }
    </script>
```

**Comment by eduardotkoller** [comment]
You can't modify the conversation form after it has been generated by the plugin script. The first dinamically created inputs are included in the conversation because they are being inserted before the convForm method, but the second is being inserted after.

This plugin was made just to transform forms into front-end chats, it was not made thinking in back-end processing during the conversation. Sorry.

**Comment by eduardotkoller** [comment]
Hello again Vijay. I was thinking again about your question and I realized that it is possible yo make it work like you described. At the moment, when the page is loaded, the plugin goes through all the inputs in the DOM and creates a linked list of states to follow, but if you change the answerWith method of the ConvState prototype (line 135 of the current script, more precisely at the lines 172 to 178), instead of making the plugin follow to the next pre-built state, you can make it do an ajax request to a server with the user response and build the next state yourself with the response from the server.

To build the next response, you can take a look at lines 188 to 224 to see how I create the input array to build the state object.

Let me know if you need more help understanding it, and thanks for the interest in the plugin!
