### ISSUE TITLE
Handling input value

### ISSUE THREAD

**Issue by krishnakanthpps** [eduardotkoller/convForm#7]
Hi.

Is it possible to handle an input text value so that it can be sent to something like an api.ai backend?
if yes, can you post a sample code.

I have tried different way to take the input and pass it to a callback function, but have not been able to do, leave alone sending it to another backend

**Comment by eduardotkoller** [comment]
Hello,

No, it isn't possible at the current state of the code to do it **asynchronously**. I didn't implement it because you can still send the info to an API, just handle the data after the form is completed and do the job you need. The callback function is implemented only at select inputs, and its there so you can do something front-end related with it.

Do you have any need to do it asynchronously?

**Comment by eduardotkoller** [comment]
Just commenting back here because it is possible now with the additions of callback functions to all questions. It's a little bit hard to fiddle with the states but at least it is possible to do this kind of thing.

**Comment by krishnakanthpps** [comment]
Thank you. Let me try to fiddle with it..




Get Outlook for Android







On Thu, Feb 22, 2018 at 7:57 AM +0530, "Eduardo Thomas Koller" <notifications@github.com> wrote:












Just commenting back here because it is possible now with the additions of callback functions to all questions. It's a little bit hard to fiddle with the states but at least it is possible to do this kind of thing.
